apiVersion: apps/v1
kind: Deployment
metadata:
  name: latin-checker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: latin-checker
  template:
    metadata:
      labels:
        app: latin-checker
    spec:
      containers:
        - name: latin-checker
          image: viktor/latin-checker:latest
          imagePullPolicy: Always
          command: ["/bin/sh", "-c"]
          args: ["/usr/local/bin/latin_checker 3 '1 2 3 2 3 1 3 1 2' && sleep infinity"]