name: CI

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repo
        uses: actions/checkout@v3

      - name: Install deps
        run: |
          sudo apt update
          sudo apt install -y make gcc golang-go

      - name: Build program
        run: bash ./cicd/build.sh

      - name: Upload build artifact
        uses: actions/upload-artifact@v3
        with:
          name: binary
          path: usr/bin/
          retention-days: 1

  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Clone repo
        uses: actions/checkout@v3

      - name: Install deps
        run: |
          sudo apt update
          sudo apt install -y make gcc golang-go

      - name: Download build artifact
        uses: actions/download-artifact@v3
        with:
          name: binary
          path: usr/bin/

      - name: Run tests
        run: bash ./cicd/test.sh

  package:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Clone repo
        uses: actions/checkout@v3

      - name: Install deps
        run: |
          sudo apt update
          sudo apt install -y dpkg-dev

      - name: Download build artifact
        uses: actions/download-artifact@v3
        with:
          name: binary
          path: usr/bin/

      - name: Build deb package
        run: bash ./cicd/package.sh

      - name: Upload deb artifact
        uses: actions/upload-artifact@v3
        with:
          name: deb-package
          path: "*.deb"
          retention-days: 1